In [1]:
import pandas as pd

## Triplet Bert Related Eval Results

In [2]:
from sklearn.metrics import accuracy_score,f1_score,recall_score,precision_score

# Tribrid

In [3]:
df = pd.read_csv("../Evaluation/imbcs_Trbrid_bs24_lr2e_5_epoch25_raw_score.csv")

In [4]:
df

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
0,-5.369023,4.494341,0.021373,0.019293,1,0,1
1,-5.343311,4.811850,0.005209,0.001241,1,0,0
2,-6.016840,5.436193,0.004681,0.006622,1,1,0
3,-6.018362,5.425450,0.001494,0.006756,1,1,1
4,-5.914725,5.461515,0.009815,1.955262,1,1,1
...,...,...,...,...,...,...,...
1187,-3.853595,3.105596,0.015429,0.025893,1,1,0
1188,-2.984922,5.092648,0.024121,1.951973,1,1,1
1189,9.055948,-5.728373,1.956075,1.898383,0,0,0
1190,-2.896666,2.634518,0.005623,0.016864,1,1,0
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0

In [5]:
df_cons = df[df.predict_label==df.distance_label]
df_cons

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
2,-6.016840,5.436193,0.004681,0.006622,1,1,0
3,-6.018362,5.425450,0.001494,0.006756,1,1,1
4,-5.914725,5.461515,0.009815,1.955262,1,1,1
5,-5.489474,4.377404,0.011542,0.026861,1,1,0
6,-5.883503,5.159852,0.004363,0.005976,1,1,1
...,...,...,...,...,...,...,...
1187,-3.853595,3.105596,0.015429,0.025893,1,1,0
1188,-2.984922,5.092648,0.024121,1.951973,1,1,1
1189,9.055948,-5.728373,1.956075,1.898383,0,0,0
1190,-2.896666,2.634518,0.005623,0.016864,1,1,0
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0

In [13]:
print(f1_score(df_cons.gold,df_cons.distance_label),
precision_score(df_cons.gold,df_cons.distance_label),
recall_score(df_cons.gold,df_cons.distance_label))

0.7305936073059361 0.7380073800738007 0.7233273056057866

# logits evaluation results

In [3560]:
f1_score(df.gold,df.predict_label)

0.7111472742066721

In [3561]:
precision_score(df.gold,df.predict_label)

0.7199341021416804

In [3562]:
recall_score(df.gold,df.predict_label)

0.702572347266881

# distance evaluation results

In [3563]:
f1_score(df.gold,df.distance_label)

0.6878980891719746

In [3564]:
precision_score(df.gold,df.distance_label)

0.6813880126182965

In [3565]:
recall_score(df.gold,df.distance_label)

0.6945337620578779

# consistent cases (logtis prediction == distance prediction)

In [3566]:
df_consistency = df[df.predict_label==df.distance_label]

In [3567]:
df_consistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
2,-6.016840,5.436193,0.004681,0.006622,1,1,0
3,-6.018362,5.425450,0.001494,0.006756,1,1,1
4,-5.914725,5.461515,0.009815,1.955262,1,1,1
5,-5.489474,4.377404,0.011542,0.026861,1,1,0
6,-5.883503,5.159852,0.004363,0.005976,1,1,1
...,...,...,...,...,...,...,...
1187,-3.853595,3.105596,0.015429,0.025893,1,1,0
1188,-2.984922,5.092648,0.024121,1.951973,1,1,1
1189,9.055948,-5.728373,1.956075,1.898383,0,0,0
1190,-2.896666,2.634518,0.005623,0.016864,1,1,0
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0

In [3568]:
f1_score(df_consistency.gold,df_consistency.distance_label)

0.7305936073059361

In [3569]:
precision_score(df_consistency.gold,df_consistency.distance_label)

0.7380073800738007

In [3570]:
recall_score(df_consistency.gold,df_consistency.distance_label)

0.7233273056057866

# Logits experiments of consistent cases

In [3571]:
df_logits_diff = df_consistency[abs(df_consistency.undermine_score-df_consistency.support_score)>11.7]
df_logits_diff

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
14,9.588130,-8.548126,1.964872,0.001022,0,0,0
24,10.445886,-9.543445,1.949151,0.000548,0,0,0
25,8.638076,-7.933535,1.909515,0.002246,0,0,0
26,10.663933,-9.564696,1.981051,0.022369,0,0,0
27,10.602495,-9.744211,1.950789,0.000726,0,0,0
...,...,...,...,...,...,...,...
1176,8.373610,-6.576835,1.910999,0.995722,0,0,0
1178,9.087031,-5.937159,1.965645,1.817730,0,0,0
1184,7.831972,-7.350706,1.943314,0.025433,0,0,1
1189,9.055948,-5.728373,1.956075,1.898383,0,0,0
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0

In [3572]:
f1_score(df_logits_diff.gold,df_logits_diff.distance_label)

0.3470319634703196

In [3573]:
precision_score(df_logits_diff.gold,df_logits_diff.distance_label)

0.9743589743589743

In [3574]:
recall_score(df_logits_diff.gold,df_logits_diff.distance_label)

0.2111111111111111

# Distance experiments of consistent cases

In [3575]:
df_distance_diff = df_consistency[abs(df_consistency.cp_distance-df_consistency.cop_distance)>1.9]
df_distance_diff

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
4,-5.914725,5.461515,0.009815,1.955262,1,1,1
14,9.588130,-8.548126,1.964872,0.001022,0,0,0
19,-5.653688,5.407442,0.013742,1.936317,1,1,0
24,10.445886,-9.543445,1.949151,0.000548,0,0,0
25,8.638076,-7.933535,1.909515,0.002246,0,0,0
...,...,...,...,...,...,...,...
1180,-3.012966,4.877105,0.025012,1.943121,1,1,0
1183,-3.055944,4.859256,0.025548,1.964957,1,1,0
1184,7.831972,-7.350706,1.943314,0.025433,0,0,1
1188,-2.984922,5.092648,0.024121,1.951973,1,1,1
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0

In [3576]:
f1_score(df_distance_diff.gold,df_distance_diff.distance_label)

0.7766599597585513

In [3577]:
precision_score(df_distance_diff.gold,df_distance_diff.distance_label)

0.7658730158730159

In [3578]:
recall_score(df_distance_diff.gold,df_distance_diff.distance_label)

0.7877551020408163

# the whole cases

In [3579]:
df_inconsistency = df

In [3580]:
df_consistency = df[df.predict_label==df.distance_label]

In [3581]:
df_inconsistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
0,-5.369023,4.494341,0.021373,0.019293,1,0,1
1,-5.343311,4.811850,0.005209,0.001241,1,0,0
2,-6.016840,5.436193,0.004681,0.006622,1,1,0
3,-6.018362,5.425450,0.001494,0.006756,1,1,1
4,-5.914725,5.461515,0.009815,1.955262,1,1,1
...,...,...,...,...,...,...,...
1187,-3.853595,3.105596,0.015429,0.025893,1,1,0
1188,-2.984922,5.092648,0.024121,1.951973,1,1,1
1189,9.055948,-5.728373,1.956075,1.898383,0,0,0
1190,-2.896666,2.634518,0.005623,0.016864,1,1,0
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0

# Consistent cases

In [3582]:
#consistent cases analysis

In [3583]:
consistent_logits_median = abs(df_consistency.undermine_score-df_consistency.support_score).median()
consistent_logits_median

11.480582

In [3584]:
consistent_logits_mean = abs(df_consistency.undermine_score-df_consistency.support_score).mean()
consistent_logits_mean

13.136183590830917

In [3585]:
consistent_logits_max =abs(df_consistency.undermine_score-df_consistency.support_score).max()
consistent_logits_max

21.927399

In [3586]:
consistent_logits_min = abs(df_consistency.undermine_score-df_consistency.support_score).min()
consistent_logits_min

0.040028400000000186

In [3587]:
consistent_distance_median = abs(df_consistency.cp_distance-df_consistency.cop_distance).median()
consistent_distance_median

1.8418612700000003

In [3588]:
consistent_distance_mean = abs(df_consistency.cp_distance-df_consistency.cop_distance).mean()
consistent_distance_mean

1.3366793045694947

In [3589]:
consistent_distance_max = abs(df_consistency.cp_distance-df_consistency.cop_distance).max()
consistent_distance_max

1.992063251476

In [3590]:
consistent_distance_min = abs(df_consistency.cp_distance-df_consistency.cop_distance).min()
consistent_distance_min

1.1600000000333566e-05

# all cases analysis

In [3591]:
inconsistent_logits_median = abs(df_inconsistency.undermine_score-df_inconsistency.support_score).median()
inconsistent_logits_median

11.3824043

In [3592]:
inconsistent_logits_mean = abs(df_inconsistency.undermine_score-df_inconsistency.support_score).mean()
inconsistent_logits_mean

12.805966802848992

In [3593]:
inconsistent_logits_max = abs(df_inconsistency.undermine_score-df_inconsistency.support_score).max()
inconsistent_logits_max

21.927399

In [3594]:
inconsistent_logits_min = abs(df_inconsistency.undermine_score-df_inconsistency.support_score).min()
inconsistent_logits_min

0.040028400000000186

In [3595]:
inconsistent_distance_median = abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance).median()
inconsistent_distance_median

1.6558347864999998

In [3596]:
inconsistent_distance_mean = abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance).mean()
inconsistent_distance_mean

1.1841946601796955

In [3597]:
inconsistent_distance_max = abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance).max()
inconsistent_distance_max

1.992063251476

In [3598]:
inconsistent_distance_min = abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance).min()
inconsistent_distance_min

1.1600000000333566e-05

In [3599]:
import flyingsquid
from numpy.random import seed, rand
import itertools
import numpy as np

In [3600]:
df_inconsistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
0,-5.369023,4.494341,0.021373,0.019293,1,0,1
1,-5.343311,4.811850,0.005209,0.001241,1,0,0
2,-6.016840,5.436193,0.004681,0.006622,1,1,0
3,-6.018362,5.425450,0.001494,0.006756,1,1,1
4,-5.914725,5.461515,0.009815,1.955262,1,1,1
...,...,...,...,...,...,...,...
1187,-3.853595,3.105596,0.015429,0.025893,1,1,0
1188,-2.984922,5.092648,0.024121,1.951973,1,1,1
1189,9.055948,-5.728373,1.956075,1.898383,0,0,0
1190,-2.896666,2.634518,0.005623,0.016864,1,1,0
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0

In [3601]:
df_inconsistency[abs(df_inconsistency.undermine_score-df_inconsistency.support_score)>5.5]

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
0,-5.369023,4.494341,0.021373,0.019293,1,0,1
1,-5.343311,4.811850,0.005209,0.001241,1,0,0
2,-6.016840,5.436193,0.004681,0.006622,1,1,0
3,-6.018362,5.425450,0.001494,0.006756,1,1,1
4,-5.914725,5.461515,0.009815,1.955262,1,1,1
...,...,...,...,...,...,...,...
1187,-3.853595,3.105596,0.015429,0.025893,1,1,0
1188,-2.984922,5.092648,0.024121,1.951973,1,1,1
1189,9.055948,-5.728373,1.956075,1.898383,0,0,0
1190,-2.896666,2.634518,0.005623,0.016864,1,1,0
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0

In [3602]:
df_inconsistency[abs(df_inconsistency.cp_distance-df_inconsistency.cop_distance)>1.6]

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold
4,-5.914725,5.461515,0.009815,1.955262,1,1,1
14,9.588130,-8.548126,1.964872,0.001022,0,0,0
19,-5.653688,5.407442,0.013742,1.936317,1,1,0
24,10.445886,-9.543445,1.949151,0.000548,0,0,0
25,8.638076,-7.933535,1.909515,0.002246,0,0,0
...,...,...,...,...,...,...,...
1184,7.831972,-7.350706,1.943314,0.025433,0,0,1
1185,-2.851288,5.024311,0.023395,1.899833,1,1,1
1186,-2.668099,4.795904,0.024899,1.837398,1,1,1
1188,-2.984922,5.092648,0.024121,1.951973,1,1,1
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0

In [3603]:
df_inconsistency["snorkel_logits_17"]=df_inconsistency.predict_label
df_inconsistency.snorkel_logits_17=df_inconsistency.apply(lambda x: -1 if x.snorkel_logits_17==0 else 1, axis=1)
df_inconsistency.snorkel_logits_17=df_inconsistency.apply(lambda x: 0 if abs(x.undermine_score-x.support_score)<4.3 else x.snorkel_logits_17, axis=1)

In [3604]:
df_inconsistency["snorkel_logits_37"]=df_inconsistency.predict_label
df_inconsistency.snorkel_logits_37=df_inconsistency.apply(lambda x: -1 if x.snorkel_logits_37==0 else 1, axis=1)
df_inconsistency.snorkel_logits_37=df_inconsistency.apply(lambda x: 0 if abs(x.undermine_score-x.support_score)<7.3 else x.snorkel_logits_37, axis=1)

In [3605]:
df_inconsistency["snorkel_logits_57"]=df_inconsistency.predict_label
df_inconsistency.snorkel_logits_57=df_inconsistency.apply(lambda x: -1 if x.snorkel_logits_57==0 else 1, axis=1)
df_inconsistency.snorkel_logits_57=df_inconsistency.apply(lambda x: 0 if abs(x.undermine_score-x.support_score)<8.3 else x.snorkel_logits_57, axis=1)

In [3606]:
df_inconsistency["snorkel_logits_77"]=df_inconsistency.predict_label
df_inconsistency.snorkel_logits_77=df_inconsistency.apply(lambda x: -1 if x.snorkel_logits_77==0 else 1, axis=1)
df_inconsistency.snorkel_logits_77=df_inconsistency.apply(lambda x: 0 if abs(x.undermine_score-x.support_score)<10.3  else x.snorkel_logits_77, axis=1)

In [3607]:
df_inconsistency["snorkel_logits_97"]=df_inconsistency.predict_label
df_inconsistency.snorkel_logits_97=df_inconsistency.apply(lambda x: -1 if x.snorkel_logits_97==0 else 1, axis=1)
df_inconsistency.snorkel_logits_97=df_inconsistency.apply(lambda x: 0 if abs(x.undermine_score-x.support_score)<13.3  else x.snorkel_logits_97, axis=1)

In [3608]:
df_inconsistency["snorkel_distance_01"]=df_inconsistency.distance_label
df_inconsistency.snorkel_distance_01=df_inconsistency.apply(lambda x: -1 if x.snorkel_distance_01==0 else 1, axis=1)
df_inconsistency.snorkel_distance_01=df_inconsistency.apply(lambda x: 0 if abs(x.cp_distance-x.cop_distance)<0.01  else x.snorkel_distance_01, axis=1)

In [3609]:
df_inconsistency["snorkel_distance_03"]=df_inconsistency.distance_label
df_inconsistency.snorkel_distance_03=df_inconsistency.apply(lambda x: -1 if x.snorkel_distance_03==0 else 1, axis=1)
df_inconsistency.snorkel_distance_03=df_inconsistency.apply(lambda x: 0 if abs(x.cp_distance-x.cop_distance)<0.2  else x.snorkel_distance_03, axis=1)

In [3610]:
df_inconsistency["snorkel_distance_05"]=df_inconsistency.distance_label
df_inconsistency.snorkel_distance_05=df_inconsistency.apply(lambda x: -1 if x.snorkel_distance_05==0 else 1, axis=1)
df_inconsistency.snorkel_distance_05=df_inconsistency.apply(lambda x: 0 if abs(x.cp_distance-x.cop_distance)<1.1 else x.snorkel_distance_05, axis=1)

In [3611]:
df_inconsistency["snorkel_distance_07"]=df_inconsistency.distance_label
df_inconsistency.snorkel_distance_07=df_inconsistency.apply(lambda x: -1 if x.snorkel_distance_07==0 else 1, axis=1)
df_inconsistency.snorkel_distance_07=df_inconsistency.apply(lambda x: 0 if abs(x.cp_distance-x.cop_distance)<1.5  else x.snorkel_distance_07, axis=1)

In [3612]:
df_inconsistency["snorkel_distance_09"]=df_inconsistency.distance_label
df_inconsistency.snorkel_distance_09=df_inconsistency.apply(lambda x: -1 if x.snorkel_distance_09==0 else 1, axis=1)
df_inconsistency.snorkel_distance_09=df_inconsistency.apply(lambda x: 0 if abs(x.cp_distance-x.cop_distance)<1.9  else x.snorkel_distance_09, axis=1)

In [3613]:
df_inconsistency["snorkel_label"]=df_inconsistency.gold
df_inconsistency.snorkel_label = df_inconsistency.apply(lambda x: -1 if x.snorkel_label==0 else 1, axis=1)

In [3614]:
df_inconsistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,snorkel_logits_17,snorkel_logits_37,snorkel_logits_57,snorkel_logits_77,snorkel_logits_97,snorkel_distance_01,snorkel_distance_03,snorkel_distance_05,snorkel_distance_07,snorkel_distance_09,snorkel_label
0,-5.369023,4.494341,0.021373,0.019293,1,0,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,-5.343311,4.811850,0.005209,0.001241,1,0,0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
2,-6.016840,5.436193,0.004681,0.006622,1,1,0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
3,-6.018362,5.425450,0.001494,0.006756,1,1,1,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,-5.914725,5.461515,0.009815,1.955262,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1187,-3.853595,3.105596,0.015429,0.025893,1,1,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1
1188,-2.984922,5.092648,0.024121,1.951973,1,1,1,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1
1189,9.055948,-5.728373,1.956075,1.898383,0,0,0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,-1
1190,-2.896666,2.634518,0.005623,0.016864,1,1,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1

In [3615]:
df_inconsistency.iloc[:,-11:-1]

,snorkel_logits_17,snorkel_logits_37,snorkel_logits_57,snorkel_logits_77,snorkel_logits_97,snorkel_distance_01,snorkel_distance_03,snorkel_distance_05,snorkel_distance_07,snorkel_distance_09
0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
1187,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1188,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
1189,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0
1190,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1191,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [3616]:
df_inconsistency.iloc[:,-11:-1].values

array([[ 1.,  1.,  1., ...,  0.,  0.,  0.],
       [ 1.,  1.,  1., ...,  0.,  0.,  0.],
       [ 1.,  1.,  1., ...,  0.,  0.,  0.],
       ...,
       [-1., -1., -1., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [-1., -1., -1., ..., -1., -1., -1.]])

In [3617]:
df_inconsistency.snorkel_label.values

array([ 1, -1, -1, ..., -1, -1, -1], dtype=int64)

In [3618]:
L_dev = df_inconsistency.iloc[:,-11:-1].values

In [3619]:
Y_dev = df_inconsistency.snorkel_label.values

In [3620]:
# df_L_train = pd.read_csv("../stance_code_local/finetuned_L_train_entiretest.csv")
df_L_train = df_inconsistency

In [3621]:
df_L_train.iloc[:,-11:-1]

,snorkel_logits_17,snorkel_logits_37,snorkel_logits_57,snorkel_logits_77,snorkel_logits_97,snorkel_distance_01,snorkel_distance_03,snorkel_distance_05,snorkel_distance_07,snorkel_distance_09
0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
1187,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1188,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
1189,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0
1190,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1191,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [3622]:
df_L_train.iloc[:,-11:-1].values

array([[ 1.,  1.,  1., ...,  0.,  0.,  0.],
       [ 1.,  1.,  1., ...,  0.,  0.,  0.],
       [ 1.,  1.,  1., ...,  0.,  0.,  0.],
       ...,
       [-1., -1., -1., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [-1., -1., -1., ..., -1., -1., -1.]])

In [3623]:
L_train = df_L_train.iloc[:,-11:-1].values

In [3624]:
from flyingsquid.label_model import LabelModel

In [3625]:
m = 10
# m = 9

label_model = LabelModel(m)

In [3626]:
label_model.fit(L_train)

In [3627]:
preds = label_model.predict(L_dev).reshape(Y_dev.shape)
accuracy = np.sum(preds == Y_dev) / Y_dev.shape[0]

# print('Label model accuracy: {}%'.format(int(100 * accuracy)))
f1_score(Y_dev,preds)

0.71161657189277

In [3628]:
majority_vote_preds = np.array([1 if pred > 0 else -1 for pred in np.sum(L_dev, axis=1)])
majority_vote_accuracy = np.sum(majority_vote_preds == Y_dev) / Y_dev.shape[0]

# print('Majority vote accuracy: {}%'.format(int(100 * majority_vote_accuracy)))
f1_score(Y_dev,majority_vote_preds)

0.7105691056910569

In [3629]:
df_inconsistency["snorkel_predict"] = preds
df_inconsistency.snorkel_predict=df_inconsistency.apply(lambda x: 0 if x.snorkel_predict==-1 else 1, axis=1)

In [3630]:
df_inconsistency

,undermine_score,support_score,cp_distance,cop_distance,predict_label,distance_label,gold,snorkel_logits_17,snorkel_logits_37,snorkel_logits_57,snorkel_logits_77,snorkel_logits_97,snorkel_distance_01,snorkel_distance_03,snorkel_distance_05,snorkel_distance_07,snorkel_distance_09,snorkel_label,snorkel_predict
0,-5.369023,4.494341,0.021373,0.019293,1,0,1,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
1,-5.343311,4.811850,0.005209,0.001241,1,0,0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,1
2,-6.016840,5.436193,0.004681,0.006622,1,1,0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1,1
3,-6.018362,5.425450,0.001494,0.006756,1,1,1,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,1
4,-5.914725,5.461515,0.009815,1.955262,1,1,1,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1187,-3.853595,3.105596,0.015429,0.025893,1,1,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1,1
1188,-2.984922,5.092648,0.024121,1.951973,1,1,1,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1,1
1189,9.055948,-5.728373,1.956075,1.898383,0,0,0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.0,0.0,0.0,0.0,-1,0
1190,-2.896666,2.634518,0.005623,0.016864,1,1,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1,1
1191,8.016406,-7.709031,1.968266,0.024982,0,0,0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,0

In [3631]:
f1_score(df_inconsistency.gold,df_inconsistency.snorkel_predict)

0.71161657189277

In [3632]:
precision_score(df_inconsistency.gold,df_inconsistency.snorkel_predict)

0.7192118226600985

In [3633]:
recall_score(df_inconsistency.gold,df_inconsistency.snorkel_predict)

0.7041800643086816